### ISSUE TITLE
初始化时出现 KeyError: 'authKey' 和 Specified client not found!

### ISSUE THREAD

**Issue by HoiGe** [ehForwarderBot/efb-qq-slave#102]
## 报错信息
```
2022-01-22 22:58:46,715 [Level 99]: __main__ (__main__.init; __main__.py:129)
     Initializing slave milkice.qq... 
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/efb_qq_slave/ClientMgr.py", line 27, in __init__
    self.client = cls(name, config, channel)
  File "/usr/local/python3/lib/python3.9/site-packages/efb_qq_plugin_mirai/mirai.py", line 56, in __init__
    self.authKey = self.client_config['authKey']
KeyError: 'authKey'

```
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/python3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/python3/lib/python3.9/site-packages/ehforwarderbot/__main__.py", line 347, in <module>
    main()
  File "/usr/local/python3/lib/python3.9/site-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/python3/lib/python3.9/site-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/python3/lib/python3.9/site-packages/efb_qq_slave/__init__.py", line 44, in __init__
    self.init_client_manager()
  File "/usr/local/python3/lib/python3.9/site-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
    self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
  File "/usr/local/python3/lib/python3.9/site-packages/efb_qq_slave/ClientMgr.py", line 30, in __init__
    raise Exception("Specified client not found!")
Exception: Specified client not found!
```
其他相关issue大概都尝试了一下 结果仍然是这样

**Comment by milkice233** [comment]
试下 `pip3 install -U git+https://github.com/ehForwarderBot/efb-qq-plugin-mirai`
然后再启动

**Comment by HoiGe** [comment]
> 试下然后再启动`pip3 install -U git+https://github.com/ehForwarderBot/efb-qq-plugin-mirai`

已尝试该操作 报错同上

**Comment by milkice233** [comment]
> github.com/ehForwarderBot/efb-qq-plugin-mirai

现在再试下？

**Comment by wym3253** [comment]
> > github.com/ehForwarderBot/efb-qq-plugin-mirai
> 
> 现在再试下？

已经尝试，仍然报错同上

**Comment by milkice233** [comment]
抱歉抱歉，请 `pip3 install -U python-mirai-core` @wym3253 @HoiGe

**Comment by HoiGe** [comment]
> 抱歉抱歉，请 `pip3 install -U python-mirai-core` @wym3253 @HoiGe

已尝试 未解决问题 报错信息没有改变

**Comment by milkice233** [comment]
抱歉，我知道什么原因了……

**Comment by milkice233** [comment]
请将配置文件中的 verifyKey 改为 authKey

**Comment by HoiGe** [comment]
> 请将配置文件中的 verifyKey 改为 authKey

问题解决了 感谢
Mirai客户端配置文档有关这部分的内容应该需要修改一下

**Comment by milkice233** [comment]
修了
