### ISSUE TITLE
遇到与 #105 相同问题（Specified client not found!）

### ISSUE THREAD

**Issue by Astrian** [ehForwarderBot/efb-qq-slave#108]
详细错误栈：

```
➜  .ehforwarderbot ehforwarderbot                                    
2022-03-04 14:08:25,224 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:129)
     Initializing slave milkice.qq... 
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.8/dist-packages/efb_qq_slave/__init__.py", line 44, in __init__
    self.init_client_manager()
  File "/usr/local/lib/python3.8/dist-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
    self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
  File "/usr/local/lib/python3.8/dist-packages/efb_qq_slave/ClientMgr.py", line 31, in __init__
    raise Exception("Specified client not found!")
Exception: Specified client not found!
```

使用的是 Mirai 客户端，Mirai 客户端配置：

``` yaml
adapters:
  - http
  - ws
enableVerify: true
verifyKey: <REDACTED>
debug: false
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
    host: localhost # 修改为 localhost 和 127.0.0.1 都无效
    port: 8080
    cors: [*]
  ws:
    host: localhost # 修改为 localhost 和 127.0.0.1 都无效
    port: 8080
    reservedSyncId: -1 
```

参考 #102 说明，对 `efb-qq-slave` 配置文件进行过修改，但依然出现同样的错误。`efb-qq-slave` 配置文件如下：

``` yaml
Client: mirai
mirai:
  qq: <REDACTED>
  host: "localhost"
  port: 8080
  authKey: <REDACTED>
  verifyKey: <REDACTED>
```

**Comment by Astrian** [comment]
确认是没有安装 `efb-qq-mirai-plugin` 的问题。安装后问题解决。
