### ISSUE TITLE
每次运行一段时间之后就会无法正常运行。但是CQ-HTTP-GO是正常的

### ISSUE THREAD

**Issue by kettly1260** [ehForwarderBot/efb-qq-slave#114]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/server.py", line 1810, in serve
    self._connections.run(self.expiration_interval)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/connections.py", line 201, in run
    self._run(expiration_interval)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/connections.py", line 218, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/connections.py", line 260, in _from_server_socket
    s, addr = server_socket.accept()
  File "/usr/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
OSError: [Errno 24] Too many open files

2022-08-03 15:18:18,168 [ERROR]: cherrypy.error (_cplogging.error; _cplogging.py:213)
    [03/Aug/2022:15:18:18] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/server.py", line 1810, in serve
    self._connections.run(self.expiration_interval)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/connections.py", line 201, in run
    self._run(expiration_interval)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/connections.py", line 218, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cheroot/connections.py", line 260, in _from_server_socket
    s, addr = server_socket.accept()
  File "/usr/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
OSError: [Errno 24] Too many open files

**Comment by milkice233** [comment]
还请给出milkice.qq文件夹下的配置和QQ客户端的配置

**Comment by milkice233** [comment]
@XYenon
